(eval-when-compile    (require 'color-theme))
(defun color-theme-eskim2 ()
  "Color theme by eskim, created 2008-07-06."
  (interactive)
  (color-theme-install
   '(color-theme-eskim2
     ((background-color . "black")
      (background-mode . dark)
      (background-toolbar-color . "red")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "white")
      (cursor-color . "white")
      (foreground-color . "#bbb")
      (mouse-color . "#1a1a1a")
      (top-toolbar-shadow-color . "#fff"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (align-highlight-change-face . highlight)
      (align-highlight-nochange-face . secondary-selection)
      (apropos-keybinding-face . underline)
      (apropos-label-face . italic)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (ispell-highlight-face . isearch)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "#bbb" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :family "bitstream-bitstream vera sans mono"))))
     (anything-header ((t (nil))))
     (bold ((t (nil))))
     (bold-italic ((t (nil))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (nil))))
     (button ((t (:bold t :weight bold))))
     (calendar-today ((t (:foreground "white"))))
     (change-log-acknowledgement ((t (nil))))
     (change-log-conditionals ((t (nil))))
     (change-log-date ((t (nil))))
     (change-log-email ((t (nil))))
     (change-log-file ((t (nil))))
     (change-log-function ((t (nil))))
     (change-log-list ((t (nil))))
     (change-log-name ((t (nil))))
     (comint-highlight-input ((t (nil))))
     (comint-highlight-prompt ((t (nil))))
     (compilation-column-number ((t (nil))))
     (compilation-error ((t (nil))))
     (compilation-info ((t (:foreground "#008ed1"))))
     (compilation-line-number ((t (nil))))
     (compilation-warning ((t (nil))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (css-property ((t (:foreground "#9651cc"))))
     (css-selector ((t (:foreground "#ffff55"))))
     (cursor ((t (:background "white"))))
     (custom-button ((t (:bold t :background "#333" :weight bold))))
     (custom-button-mouse ((t (:bold t :background "#333" :foreground "white" :weight bold))))
     (custom-button-pressed ((t (:bold t :weight bold :background "#333"))))
     (custom-documentation ((t (:foreground "#b9FC6D"))))
     (custom-face-tag-face ((t (:bold t :weight bold :foreground "#008ed1"))))
     (custom-group-tag ((t (:bold t :foreground "#ffff55" :weight bold :height 1.2))))
     (custom-link ((t (:underline t :foreground "white"))))
     (custom-state ((t (:foreground "#777"))))
     (custom-variable-tag ((t (:bold t :foreground "#008ed1" :weight bold))))
     (diff-added ((t (nil))))
     (diff-changed ((t (nil))))
     (diff-context ((t (nil))))
     (diff-file-header ((t (nil))))
     (diff-function ((t (nil))))
     (diff-header ((t (nil))))
     (diff-hunk-header ((t (nil))))
     (diff-index ((t (nil))))
     (diff-indicator-added ((t (nil))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (nil))))
     (diff-nonexistent ((t (nil))))
     (diff-refine-change ((t (nil))))
     (diff-removed ((t (nil))))
     (dired-directory ((t (:foreground "#008ed1"))))
     (dired-flagged ((t (:background "#333"))))
     (dired-header ((t (:foreground "white"))))
     (dropdown-list-face ((t (nil))))
     (dropdown-list-selection-face ((t (nil))))
     (escape-glyph ((t (nil))))
     (eshell-ls-archive ((t (:underline t :foreground "#ee3c3c" :underline nil))))
     (eshell-ls-directory ((t (:foreground "#008ed1"))))
     (eshell-prompt ((t (:foreground "white"))))
     (file-name-shadow ((t (nil))))
     (fixed-pitch ((t (nil))))
     (flymake-errline ((t (nil))))
     (flymake-warnline ((t (nil))))
     (flyspell-duplicate ((t (:background "#333"))))
     (flyspell-incorrect ((t (:background "#333"))))
     (font-lock-builtin-face ((t (:foreground "#5555ff"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#008ed1"))))
     (font-lock-comment-face ((t (:foreground "#008ed1"))))
     (font-lock-constant-face ((t (:foreground "#9651cc"))))
     (font-lock-doc-face ((t (:foreground "#777"))))
     (font-lock-function-name-face ((t (:foreground "#55ff55"))))
     (font-lock-keyword-face ((t (:foreground "#ff5555"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (nil))))
     (font-lock-regexp-grouping-construct ((t (nil))))
     (font-lock-string-face ((t (:foreground "#ffff55"))))
     (font-lock-type-face ((t (:foreground "#b9FC6D"))))
     (font-lock-variable-name-face ((t (:foreground "#ff55ff"))))
     (font-lock-warning-face ((t (nil))))
     (fringe ((t (:background "#000" :foreground "#444"))))
     (haml-tab-face ((t (nil))))
     (header-line ((t (:background "#333"))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:foreground "white" :background "#777"))))
     (highline-face ((t (:background "#222"))))
     (ido-first-match ((t (:foreground "white"))))
     (ido-incomplete-regexp ((t (nil))))
     (ido-indicator ((t (nil))))
     (ido-only-match ((t (:foreground "#b9FC6D"))))
     (ido-subdir ((t (:foreground "#008ed1"))))
     (info-xref-face ((t (:foreground "#b9FC6D"))))
     (isearch ((t (:background "#777" :foreground "white"))))
     (isearch-fail ((t (:foreground "#ee3c3c" :underline t))))
     (italic ((t (nil))))
     (lazy-highlight ((t (:background "#333"))))
     (lazy-highlight-face ((t (:background "#333"))))
     (link ((t (:foreground "white" :underline t))))
     (link-visited ((t (nil))))
     (match ((t (:foreground "white" :background "#777"))))
     (menu ((t (:background "#333"))))
     (minibuffer-noticeable-prompt ((t (:foreground "#777"))))
     (minibuffer-prompt ((t (:foreground "#777"))))
     (mlinks-link ((t (nil))))
     (mode-line ((t (:background "#333"))))
     (mode-line-buffer-id ((t (nil))))
     (mode-line-highlight ((t (:foreground "#b9FC6D"))))
     (mode-line-inactive ((t (:background "#111" :foreground "#444"))))
     (modeline-mousable ((t (:foreground "#777"))))
     (modeline-mousable-minor-mode ((t (:foreground "#777"))))
     (mouse ((t (:background "#1a1a1a"))))
     (mpg123-face-cur ((t (:foreground "#b9FC6D"))))
     (mpg123-face-indicator ((t (:foreground "#008ed1"))))
     (mpg123-face-slider ((t (:bold t :foreground "#008ed1" :weight bold))))
     (next-error ((t (nil))))
     (nobreak-space ((t (nil))))
     (nxml-attribute-local-name-face ((t (:foreground "#00bb00"))))
     (nxml-attribute-value-face ((t (:foreground "#ffff55"))))
     (nxml-comment-content-face ((t (:foreground "#008ed1"))))
     (nxml-delimiter-face ((t (:foreground "#555"))))
     (nxml-element-local-name-face ((t (:foreground "#555" :weight normal))))
     (nxml-prolog-keyword-face ((t (nil))))
     (nxml-prolog-literal-content-face ((t (nil))))
     (nxml-tag-slash-face ((t (:foreground "#555"))))
     (nxml-text-face ((t (nil))))
     (org-agenda-structure ((t (:foreground "#008ed1"))))
     (org-column ((t (:background "#222" :foreground "white"))))
     (org-date ((t (:foreground "#777"))))
     (org-done ((t (:bold t :foreground "#555" :weight bold))))
     (org-done-headline ((t (nil))))
     (org-ellipsis ((t (:foreground "white"))))
     (org-headline-done ((t (:foreground "#555"))))
     (org-hide ((t (:foreground "black"))))
     (org-level-1 ((t (:foreground "#5555ff"))))
     (org-level-2 ((t (:bold t :foreground "#ffff55" :weight bold))))
     (org-level-3 ((t (:foreground "#008ed1"))))
     (org-level-4 ((t (:foreground "#ff55ff"))))
     (org-level-5 ((t (:foreground "#b9FC6D"))))
     (org-level-6 ((t (nil))))
     (org-link ((t (:underline t :foreground "white"))))
     (org-scheduled ((t (:foreground "#00bb00"))))
     (org-scheduled-previously ((t (:foreground "#00bb00"))))
     (org-scheduled-today ((t (:foreground "#55ff55"))))
     (org-special-keyword ((t (:foreground "#55ff55"))))
     (org-table ((t (:foreground "#555"))))
     (org-tag ((t (:foreground "#55ff55"))))
     (org-time-grid ((t (:foreground "#555"))))
     (org-todo ((t (:foreground "#ff5555"))))
     (org-upcoming-deadline ((t (:foreground "#ff5555"))))
     (org-warning ((t (:underline t :foreground "#ee3c3c" :underline nil))))
     (query-replace ((t (nil))))
     (region ((t (:background "#333"))))
     (rng-error-face ((t (:underline t :foreground "#ee3c3c"))))
     (scroll-bar ((t (nil))))
     (search-buffers-face ((t (:foreground "white" :background "#777"))))
     (search-buffers-header-face ((t (:background "#333"))))
     (secondary-selection ((t (:background "#333"))))
     (shadow ((t (nil))))
     (show-paren-match ((t (:bold t :foreground "white" :weight bold))))
     (show-paren-mismatch ((t (:underline t :foreground "#ee3c3c"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-reference-face ((t (nil))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (nil))))
     (sldb-restart-type-face ((t (nil))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (nil))))
     (slime-highlight-edits-face ((t (nil))))
     (slime-highlight-face ((t (nil))))
     (slime-inspector-action-face ((t (nil))))
     (slime-inspector-label-face ((t (nil))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (nil))))
     (slime-inspector-value-face ((t (nil))))
     (slime-note-face ((t (nil))))
     (slime-reader-conditional-face ((t (nil))))
     (slime-repl-input-face ((t (nil))))
     (slime-repl-inputed-output-face ((t (:foreground "#b9FC6D"))))
     (slime-repl-output-face ((t (nil))))
     (slime-repl-output-mouseover-face ((t (nil))))
     (slime-repl-prompt-face ((t (:foreground "#008ed1"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (nil))))
     (slime-warning-face ((t (nil))))
     (speedbar-button-face ((t (nil))))
     (speedbar-directory-face ((t (:background "grey10" :foreground "grey50" :height 0.9))))
     (speedbar-file-face ((t (:height 0.9))))
     (speedbar-highlight-face ((t (:bold t :foreground "white" :weight bold))))
     (speedbar-selected-face ((t (:bold t :foreground "white" :background "#777" :weight bold :height 0.9))))
     (speedbar-separator-face ((t (:foreground "#555" :background "#555" :height 0.9))))
     (speedbar-tag-face ((t (:foreground "#b9FC6D" :height 0.9))))
     (svn-status-blame-highlight-face ((t (nil))))
     (svn-status-blame-rev-number-face ((t (nil))))
     (svn-status-directory-face ((t (nil))))
     (svn-status-filename-face ((t (nil))))
     (svn-status-locked-face ((t (nil))))
     (svn-status-marked-face ((t (nil))))
     (svn-status-marked-popup-face ((t (nil))))
     (svn-status-switched-face ((t (nil))))
     (svn-status-symlink-face ((t (nil))))
     (svn-status-update-available-face ((t (nil))))
     (tabbar-button-face ((t (:background "#222" :height 0.8))))
     (tabbar-default-face ((t (:background "#222" :height 0.8))))
     (tabbar-selected-face ((t (:foreground "white" :background "#777" :height 0.8))))
     (tabbar-separator-face ((t (:background "#222" :height 0.7))))
     (tabbar-unselected-face ((t (:background "#333" :height 0.8))))
     (tool-bar ((t (:background "#333"))))
     (tooltip ((t (:foreground "#333"))))
     (trailing-whitespace ((t (nil))))
     (underline ((t (nil))))
     (variable-pitch ((t (nil))))
     (vertical-border ((t (nil))))
     (widget-button ((t (nil))))
     (widget-button-pressed ((t (nil))))
     (widget-documentation ((t (nil))))
     (widget-field ((t (:background "#222" :foreground "#555"))))
     (widget-inactive ((t (nil))))
     (widget-link ((t (:underline t :foreground "white"))))
     (widget-single-line-field ((t (nil))))
     (woman-addition ((t (nil))))
     (woman-bold ((t (nil))))
     (woman-italic ((t (nil))))
     (woman-unknown ((t (nil))))
     (yas/field-highlight-face ((t (nil))))
     (yas/mirror-highlight-face ((t (nil)))))))
(add-to-list 'color-themes '(my-color-theme  "eskim2" "eskim"))